Repository YoungVision-eV/website-cms, pull requests merged in 2024-05, with the labels that each got.

#3 feat(app): add events collection
  package.json
  pnpm-lock.yaml
  src/collections/Events.ts
  src/payload-types.ts
  src/payload.config.ts
Labels: 5 min review, dependencies

#8 Han2 ro/feat/create media collection
  .gitignore
  docker-compose.yml
  package.json
  src/collections/Events.ts
  src/collections/Media.ts
  src/payload-types.ts
  src/payload.config.ts
Labels: 5 min review, dependencies

#10 feat(app): add calendarCover field in Events
  package.json
  src/collections/Events.ts
  src/collections/Media.ts
  src/payload-types.ts
Labels: dependencies, 1 min review

#11 feat(app): 7 add all missing event fields
  src/collections/Events.ts
Labels: 10 min review

#12 fix(app): set slug required to false
  src/collections/Events.ts
Labels: 1 min review

#18 feat(app): add registration link + update types
  src/collections/Events.ts
  src/payload-types.ts
  src/payload.config.ts
Labels: 1 min review

#14 ci(server): add health checks for payload
  docker-compose.yml
  src/payload.config.ts
Labels: 1 min review
